Algoritmo "crescente"

Var
 x, y : inteiro

Inicio

  escreva ("Digite dois numeros: ")
  leia (x)
  leia(y)
  
  enquanto x <> y faca
           se x < y entao
              escreval ("CRESCENTE")
           senao
              escreval ("DECRESCENTE")
           fimse
           

           escreva ("Digite dois numeros: ")
           leia (x)
           leia(y)
  fimenquanto
  
  escreval ("X e Y sao iguais!")


Fimalgoritmo